SecondWeb/Models/ErrorViewModel.cs
namespace SecondWeb.Models {
    public class ErrorViewModel {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SecondWeb/Models/ModelData.cs
namespace SecondWeb.Models {
    public class ModelData { 
            public DateTime _dT;
            public string _appEnv;
            public string _appName;
            public string _appHost;
            public string _appProtocol;
    }
}

SecondWeb/Controllers/HomeController.cs
using SecondWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace SecondWeb.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public HomeController(ILogger<HomeController> logger, IHttpContextAccessor httpContextAccessor) {
            _logger = logger;
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index() {
           return View();
        }

        public IActionResult Privacy() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SecondWeb/Controllers/IndexController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace SecondWeb.Controllers {
    public class IndexController : Controller {
      
        public ActionResult Index() {
            return View();
        }

        public ActionResult Details(int id) {
            return View();
        }
        public ActionResult Create() {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection) {
            try {
                return RedirectToAction(nameof(Index));
            }
            catch {
                return View();
            }
        }

        public ActionResult Edit(int id) {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection) {
            try {
                return RedirectToAction(nameof(Index));
            }
            catch {
                return View();
            }
        }

        public ActionResult Delete(int id) {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection) {
            try {
                return RedirectToAction(nameof(Index));
            }
            catch {
                return View();
            }
        }
    }
}

SecondWeb/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using SecondWeb.Models;
using System.Text.Json;

namespace SecondWeb.Controllers {
    [Serializable]
    public class TaskController : Controller {
        private readonly ILogger<TaskController> _logger;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public TaskController(ILogger<TaskController> logger, IWebHostEnvironment webHostEnvironment) {
            _logger = logger;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Task1() {
            ModelData model = new ModelData();
            model._dT = DateTime.Now;
            model._appEnv = _webHostEnvironment.EnvironmentName;
            model._appName = _webHostEnvironment.ApplicationName; 
            model._appHost = this.Request.Host.Value;
            model._appProtocol = this.Request.Protocol;
            return View(model);
        }
        public IActionResult Task2() {


            ViewBag.JsonString = JsonSerializer.Serialize(new IndexController());
            
            return View();


        }
        public IActionResult Task3(string str1, int str2, double str3) {
            ViewData["str1"] = str1;
            ViewData["str2"] = str2;
            ViewData["str3"] = str3;
            return View();
        }
    }
}

SecondWeb/Views/Home/Index.cshtml
@model SecondWeb.Models.ModelData
@{
    ViewData["Title"] = "Home Page";
}

SecondWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SecondWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SecondWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SecondWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Task1">Task1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Task2">Task2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Task3">Task3</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SecondWeb/Views/Task/Task1.cshtml
@model SecondWeb.Models.ModelData
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-left">
    <h2>Name:</h2><h3>Natyazhenko Vladimir</h3>
    <h2>Date:</h2><h3>@Model._dT</h3>
    <h2>Enviroment:</h2><h3>@Model._appEnv</h3>
    <h2>ApplicationName:</h2><h3>@Model._appName</h3>
    <h2>Host:</h2><h3>@Model._appHost</h3>
    <h2>Protocol:</h2><h3>@Model._appProtocol</h3>
</div>

SecondWeb/Views/Task/Task2.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-left">
    <p>@ViewBag.JsonString</p>
</div>

SecondWeb/Views/Task/Task3.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-left">
    <h2>Name: @ViewData["str1"]</h2>
    <h2>Age: @ViewData["str2"]</h2>
    <h2>Height: @ViewData["str3"]</h2>
    <div style="text-align: left">
    <form asp-controller="Task" asp-action="Task3" method="post">
          Name:         <input name="str1" /><br />
          Age:          <input name="str2" /><br />
          Height(double):  <input name="str3" /><br />
          <button type="submit">Task3</button>
      </form> 
      </div>
</div>